
-- Insertando datos en la tabla TURNO_LABORAL
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('mañana', 8);
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('tarde', 13);
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('noche', 18);
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('todo el dia', null);

-- Insertando datos en la tabla TIEMPO_POR_CONSULTA
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (15);
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (20);
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (30);
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (45);

-- Insertando datos en la tabla DIA_LABORAL
INSERT INTO DIA_LABORAL (DIA) VALUES ('Lunes');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Martes');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Miercoles');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Jueves');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Viernes');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Sábado');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Domingo');

-- Insertando datos en la tabla MODALIDAD
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ('Presencial');
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ('Virtual');

-- Insertando datos en la tabla ESPECIALIDAD
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Cardiologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Dermatologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Endocrinologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Gastroenterologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Hematologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Infectologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Nefrologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Neumologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Neurologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Oncologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Oftalmologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Otorrinolaringologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Pediatria', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Psiquiatria', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Reumatologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Traumatología', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Ginecología', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Urología', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Radiología', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Dentistería', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Ortopedia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Oncología Pediátrica', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Neurocirugía', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Oncología Radioterápica', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Cirugía Plástica', 1);


-- Insertando datos en la tabla SUCURSAL
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Santa Fe', 1234, 'La Plata');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('9 de Julio', 5678, 'Mar del Plata');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Rivadavia', 9101, 'Bahía Blanca');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Belgrano', 1121, 'Tandil');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Pueyrredón', 3141, 'Olavarria');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Avellaneda', 5161, 'Junín');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Alsina', 7181, 'Necochea');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('San Martín', 9202, 'San Nicolás');



-- Insertando datos en la tabla MES_LABORAL
INSERT INTO MES_LABORAL (MES) VALUES ('Enero');
INSERT INTO MES_LABORAL (MES) VALUES ('Febrero');
INSERT INTO MES_LABORAL (MES) VALUES ('Marzo');
INSERT INTO MES_LABORAL (MES) VALUES ('Abril');
INSERT INTO MES_LABORAL (MES) VALUES ('Mayo');
INSERT INTO MES_LABORAL (MES) VALUES ('Junio');
INSERT INTO MES_LABORAL (MES) VALUES ('Julio');
INSERT INTO MES_LABORAL (MES) VALUES ('Agosto');
INSERT INTO MES_LABORAL (MES) VALUES ('Septiembre');
INSERT INTO MES_LABORAL (MES) VALUES ('Octubre');
INSERT INTO MES_LABORAL (MES) VALUES ('Noviembre');
INSERT INTO MES_LABORAL (MES) VALUES ('Diciembre');





-- Insertando datos en la tabla Professional
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Ernesto', 'Strange', 12345678, 1111111111, 1, 1, 8, 1, 1, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Facundo', 'Goku', 12345678, 1123421211, 1, 1, 1, 1, 2, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Martin', 'Who', 23456789, 1222222222, 2, 2, 1, 2, 3, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Juan', 'Doom', 34567890, 1333333333, 3, 3, 1, 3, 4, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Pablo', 'Octopus', 45678901, 1444444444, 4, 4, 8, 4, 4, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Alexis', 'X', 56789012, 1555555555, 1, 5, 6, 1, 5, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Mario', 'House', 67890123, 1666666666, 2, 6, 7, 2, 6, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Mariano', 'Watson', 78901234, 1777777777, 3, 7, 8, 3, 7, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Banner', 89012345, 1888888888, 4, 8, 6, 4, 8, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Fate', 90123456, 1999999999, 1, 9, 7, 1, 9, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Midnight', 12345670, 1010101010, 2, 10, 8, 2, 10, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Star', 23456701, 1111111222, 3, 11, 6, 3, 11, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Rocket', 34567012, 1222222333, 4, 12, 7, 4, 12, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Groot', 45670123, 1333333444, 1, 13, 8, 1, 13, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Panther', 56701234, 1444444555, 2, 14, 6, 2, 14, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('María', 'González', 22334455, 1111111222, 3, 11, 6, 3, 11, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Juan', 'Martínez', 33445566, 1222222333, 4, 12, 7, 4, 12, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Laura', 'López', 44556677, 1333333444, 1, 13, 8, 1, 13, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Carlos', 'Rodríguez', 55667788, 1444444555, 2, 14, 6, 2, 14, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Ana', 'Pérez', 66778899, 1555555666, 3, 1, 7, 3, 1, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Miguel', 'Fernández', 77889900, 1666666777, 1, 2, 8, 1, 2, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Cecilia', 'Gómez', 88990011, 1777777888, 2, 3, 6, 2, 3, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Martín', 'López', 99001122, 1888888999, 3, 4, 7, 3, 4, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Silvia', 'Rodríguez', 10112233, 1999999000, 4, 5, 8, 4, 5, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Javier', 'Pérez', 11223344, 1000000111, 1, 6, 6, 1, 6, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Gabriela', 'Fernández', 22334455, 1111111222, 3, 7, 7, 3, 7, 1);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Andrés', 'Gómez', 33445566, 1222222333, 4, 8, 8, 4, 8, 2);
INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Elena', 'López', 44556677, 1333333444, 1, 9, 6, 1, 9, 1);







INSERT INTO USUARIO (NOMBRE, APELLIDO, DNI, TELEFONO) VALUES ('Axel', 'Fernandez', 110931821, '1193877611');
