
-- Insertando datos en la tabla WorkingShift
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('mañana', 8);
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('tarde', 13);
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('noche', 18);
INSERT INTO TURNO_LABORAL (TURNO, HORARIO_ENTRADA) VALUES ('todo el dia', null);

-- Insertando datos en la tabla TimeConsultation
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (15);
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (20);
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (30);
INSERT INTO TIEMPO_POR_CONSULTA (MINUTOS) VALUES (45);

-- Insertando datos en la tabla WorkingDay
INSERT INTO DIA_LABORAL (DIA) VALUES ('Lunes');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Martes');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Miercoles');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Jueves');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Viernes');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Sábado');
INSERT INTO DIA_LABORAL (DIA) VALUES ('Domingo');

-- Insertando datos en la tabla Modality
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ('Presencial');
INSERT INTO MODALIDAD (DESCRIPCION) VALUES ('Virtual');

-- Insertando datos en la tabla Specialization
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Cardiologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Dermatologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Endocrinologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Gastroenterologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Hematologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Infectologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Nefrologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Neumologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Neurologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Oncologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Oftalmologia', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Otorrinolaringologia', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Pediatria', 1);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Psiquiatria', 2);
INSERT INTO ESPECIALIDAD (DESCRIPCION, MODALIDAD_ID) VALUES ('Reumatologia', 1);

-- Insertando datos en la tabla MedicalBranch
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Santa Fe', 1234, 'La Plata');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('9 de Julio', 5678, 'Mar del Plata');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Rivadavia', 9101, 'Bahía Blanca');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Belgrano', 1121, 'Tandil');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Pueyrredón', 3141, 'Olavarria');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Avellaneda', 5161, 'Junín');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('Alsina', 7181, 'Necochea');
INSERT INTO SUCURSAL (calle, numero, localidad) VALUES ('San Martín', 9202, 'San Nicolás');


INSERT INTO MES_LABORAL (MES) VALUES ('Enero');
INSERT INTO MES_LABORAL (MES) VALUES ('Febrero');
INSERT INTO MES_LABORAL (MES) VALUES ('Marzo');
INSERT INTO MES_LABORAL (MES) VALUES ('Abril');
INSERT INTO MES_LABORAL (MES) VALUES ('Mayo');
INSERT INTO MES_LABORAL (MES) VALUES ('Junio');
INSERT INTO MES_LABORAL (MES) VALUES ('Julio');
INSERT INTO MES_LABORAL (MES) VALUES ('Agosto');
INSERT INTO MES_LABORAL (MES) VALUES ('Septiembre');
INSERT INTO MES_LABORAL (MES) VALUES ('Octubre');
INSERT INTO MES_LABORAL (MES) VALUES ('Noviembre');
INSERT INTO MES_LABORAL (MES) VALUES ('Diciembre');






INSERT INTO PROFESSIONAL (NOMBRE, APELLIDO, DNI, TELEFONO, TURNO_LABORAL_ID, ESPECIALIDAD_ID, HORAS_TRABAJADAS_POR_DIA, TIEMPO_POR_CONSULTA_ID, SUCURSAL_ID, MODALIDAD_ID) VALUES ('Doctor', 'Strange', 12345678, 1111111111, 1, 1, 8, 1, 1, 1);

INSERT INTO USUARIO (NOMBRE, APELLIDO, DNI, TELEFONO) VALUES ('Axel', 'Cespedes', 40391005, '1166710974');
